F360System/Models/Mapping.cs
using System.Collections;

namespace F360System.Models
{
    public class Mapping
    {
        public int EVId { get; set; }
        public int HId { get; set; }
        public string EId { get; set; }


        public string EmpName { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public DateTime DateFrom { get; set; } = DateTime.Today;
        public DateTime DateTo { get; set; } = DateTime.Today;
        public DateTime DeadLine { get; set; } = DateTime.Today;

        public string Status { get; set; }
        public string AcknowledgeBy { get; set; }
        public DateTime AcknowledgeDate { get; set; }

        public string AcknowledgeName { get; set; }


        public IEnumerable<Mapping> map { get; set; }
        public IEnumerable<EmpMaster> EmpList { get; set; }

        public IEnumerable<EmpMaster> HeadList { get; set; }


        public IEnumerable<MapDetails> MapDetails { get; set; }
    
        public MapDetails mapDetails { get; set; }

        public IEnumerable<Questionaire> FormHeader { get; set; }

        public IEnumerable<SubordinateView> subordinate { get; set; }



    }

    public class EmpMaster
    {
        public string EId { get; set; }
        public string EmpName { get; set; }

    }


    public class SubordinateView
    {
        public string EId { get; set; }
        public string EmpName { get; set; }

        public string sub { get; set; }

    }

    public class MapDetails
    {
        public string Relation { get; set; }
        public string Ratee { get; set; }
        public string RateeName { get; set; }
        public string RateeId { get; set; }



    }






}

F360System/Controllers/MappingController.cs
using Azure;
using Dapper;
using F360System.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Data;
using System.Security.Claims;
using System.Security.Cryptography;

namespace F360System.Controllers
{
    public class MappingController : Controller
    {
        SqlConnection db, adb;
        private string _webHostEnvironment;
        public MappingController(IConfiguration configuration, IWebHostEnvironment env)
        {
            db = new SqlConnection(configuration.GetConnectionString("DefaultConnection"));
            _webHostEnvironment = env.WebRootPath;

        }
        public IActionResult Index()
        {
            ViewBag.map = "active";
            string sql;
            Mapping mapping = new Mapping();
            var eid = HttpContext.User.FindFirstValue("eid");
            mapping.map = db.Query<Mapping>("sp_360_EvalHeader_List");

            mapping.EmpList = db.Query<EmpMaster>("SELECT eid EId, name EmpName FROM employee_master");
            mapping.FormHeader = db.Query<Questionaire>("SELECT * FROM F360_FormHeader");

           



            return View(mapping);
        }

        [Route("/Mapping/Details/{EVId}")]
        public IActionResult Details(int EVId)
        {
            ViewBag.map = "active";
            string sql;
            Mapping mapping = new Mapping();
            var name = HttpContext.User.FindFirstValue(ClaimTypes.Name);

            mapping = db.QueryFirst<Mapping>("sp_360_EvalHeader_Select", new { EVId });

            mapping.MapDetails = db.Query<MapDetails>(@"Select a.EvID, a.Relation,a.EvID,b.name as RateeName, a.RateeID Ratee from F360_EvalMapping a
                                                        JOIN employee_master b
                                                        on a.RateeID = b.eid
                                                        where EVId = @EVId", new { EVId });

            mapping.EmpList = db.Query<EmpMaster>("SELECT eid EId, name EmpName FROM employee_master where name <> @EmpName and IsActive = 1", new { mapping.EmpName });

            return View(mapping);
        }


        //header save
        public IActionResult AddEvalHeader(Mapping mapping)
        {
            var response = db.ExecuteScalar("sp_360_EvalHeader_Add", new
            {
                mapping.HId,
                mapping.EId,
                mapping.Description,
                mapping.Remarks,
                mapping.DateFrom,
                mapping.DateTo,
                mapping.DeadLine,
                CrtdBy = HttpContext.User.FindFirstValue(ClaimTypes.Name)
            }, commandType: System.Data.CommandType.StoredProcedure);


            if (response.ToString() == "Successful") // Assuming the query will affect only one row
            {
                TempData["Success Title"] = "Successfully Added New Evaluation Header";
                TempData["Success Message"] = "Header has been Added.";
                return RedirectToAction("Index");

            }

            TempData["Error Title"] = "New Evaluation HeaderFailed to add";
            TempData["Error Message"] = response.ToString();
            return RedirectToAction("Index");

        }




        //Mapping save
        public IActionResult SaveMapping(Mapping mapping)
        {
            var response = db.ExecuteScalar("sp_360_EvalMapping_Add", new
            {
                mapping.EVId,
                mapping.mapDetails.Relation,
                mapping.mapDetails.Ratee,
                CrtdBy = HttpContext.User.FindFirstValue(ClaimTypes.Name),
            }, commandType: System.Data.CommandType.StoredProcedure);


            if (response.ToString() == "Successful") // Assuming the query will affect only one row
            {
                TempData["Success Title"] = "Successfully Added employee mapping";
                TempData["Success Message"] = "Employee mapping has been Added.";
                return RedirectToAction("Details", new { mapping.EVId });

            }

            TempData["Error Title"] = "Employee mapping failed to add";
            TempData["Error Message"] = response.ToString();
            return RedirectToAction("Details", new { mapping.EVId });

        }

        //Mapping save
        public IActionResult EditMapping(Mapping mapping)
        {
            var response = db.ExecuteScalar("sp_360_EvalMapping_Edit", new
            {
                mapping.EVId,
                mapping.mapDetails.Relation,
                mapping.mapDetails.Ratee,
                CrtdBy = HttpContext.User.FindFirstValue(ClaimTypes.Name),
            }, commandType: System.Data.CommandType.StoredProcedure);


            if (response.ToString() == "Successful") // Assuming the query will affect only one row
            {
                TempData["Success Title"] = "Successfully edited employee mapping";
                TempData["Success Message"] = "Mapping has been updated.";
                return RedirectToAction("Details", new { mapping.EVId });

            }

            TempData["Error Title"] = "Employee mapping Failed to edit";
            TempData["Error Message"] = response.ToString();
            return RedirectToAction("Details", new { mapping.EVId });

        }
        //Mapping Delete
        public IActionResult DeleteMapping(Mapping mapping)
        {
            var response = db.ExecuteScalar("sp_360_EvalMapping_Delete", new
            {
                mapping.EVId,
                mapping.mapDetails.Ratee,
                CrtdBy = HttpContext.User.FindFirstValue(ClaimTypes.Name),
            }, commandType: System.Data.CommandType.StoredProcedure);


            if (response.ToString() == "Successful") // Assuming the query will affect only one row
            {
                TempData["Success Title"] = "Successfully Deleted from Mapping Header";
                TempData["Success Message"] = "Map has been Deleted.";
                return RedirectToAction("Details", new { mapping.EVId });

            }

            TempData["Error Title"] = "Deletion of Mapping failed";
            TempData["Error Message"] = response.ToString();
            return RedirectToAction("Details", new { mapping.EVId });

        }


        public IActionResult DeleteEvalHeader(Mapping mapping)
        {
            var response = db.ExecuteScalar("sp_360_EvalHeader_Delete", new
            {
                mapping.EVId,
                CrtdBy = HttpContext.User.FindFirstValue(ClaimTypes.Name),
            }, commandType: System.Data.CommandType.StoredProcedure);


            if (response.ToString() == "Successful") // Assuming the query will affect only one row
            {
                TempData["Success Title"] = "Successfully Deleted from Mapping Header";
                TempData["Success Message"] = "Map has been Deleted.";
                return RedirectToAction("Index");

            }

            TempData["Error Title"] = "Deletion of Mapping failed";
            TempData["Error Message"] = response.ToString();
            return RedirectToAction("Index");

        }




        public IActionResult EditEvalHeader(Mapping mapping) 
        {
            var response = db.ExecuteScalar("sp_360_EvalHeader_Edit", new
            {
                mapping.EVId,
                mapping.Description,
                mapping.Remarks,
                mapping.DateFrom,
                mapping.DateTo,
                mapping.DeadLine,
                CrtdBy = HttpContext.User.FindFirstValue(ClaimTypes.Name),
                mapping.AcknowledgeBy

            }, commandType: System.Data.CommandType.StoredProcedure);

            if (response.ToString() == "Successful") // Assuming the query will affect only one row
            {
                TempData["Success Title"] = "Successfully Edit Evaluation Header";
                TempData["Success Message"] = "Header has been Edited.";
                return RedirectToAction("Index");

            }

            TempData["Error Title"] = "Evaluation Header failed to edit";
            TempData["Error Message"] = response.ToString();
            return RedirectToAction("Index");
        }







        public JsonResult GetHead(string EVId)
        {
            var headList = db.Query<EmpMaster>(@"
                                                 SELECT b.name AS EmpName, a.RateeID AS EId 
                                                 FROM F360_EvalMapping a
                                                 JOIN employee_master b ON a.RateeID = b.eid
                                                 WHERE EvID = @EVId and Relation = 'Head'
                                                ", new { EVId });

            return Json(headList);
        }

    }
}

F360System/Views/Mapping/Details.cshtml
@{
    ViewData["Title"] = "Mapping Details Page";
}


@model Mapping

<div class="page-header d-print-none">
    <div class="container-xxl">
        <div class="row g-2 align-items-center">
            <div class="col-6">
                <!-- Page pre-title -->
                <div class="page-pretitle">
                    Details - Mapping
                    <h2 class="page-title">
                        Details of Mapped Employees
                    </h2>
                </div>
            </div>

            <div class="col-auto ms-auto d-print-none">

                <!-- Add Button to Open Modal -->
                <a type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#mapModal">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-bubble-text"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M7 10h10" /><path d="M9 14h5" /><path d="M12.4 3a5.34 5.34 0 0 1 4.906 3.239a5.333 5.333 0 0 1 -1.195 10.6a4.26 4.26 0 0 1 -5.28 1.863l-3.831 2.298v-3.134a2.668 2.668 0 0 1 -1.795 -3.773a4.8 4.8 0 0 1 2.908 -8.933a5.33 5.33 0 0 1 4.287 -2.16" /></svg>
                    Add
                </a>

            </div>

        </div>

    </div>
</div>


<div class="page-body">
    <div class="container-xxl">

        <div class="card">
            <div class="card-header d-block">
                <h2 class="card-title">@Model.EmpName </h2>
                <div>@Model.EId</div>
                <div>@Model.Description</div>
            </div>
            <div class="table-responsive">
                <table class="table text-muted table-mobile-sm" id="datatable" data-filename="Category">
                    <thead class="table-thead">
                        <tr>

                            <th>Relation</th>
                            <th>Ratee</th>
                            <th>Action</th>

                        </tr>

                    </thead>

                    <tbody class="table-tbody">
                        @if (Model.MapDetails == null || !Model.MapDetails.Any())
                        {
                            <tr>
                                <td colspan="3" class="text-center">NO DATA AVAILABLE</td>
                            </tr>
                        }
                        @foreach (var row in Model.MapDetails)
                        {
                            <tr>
                                @* add edit-details in class for modal*@
                                <td data-label="Relation">
                                    <a type="button" class="edit-details text-decoration-none theme-text"
                                       data-rid="@row.Ratee"
                                       data-relation="@row.Relation"
                                       data-name="@row.Ratee">
                                        
                                        @row.Relation
                                    </a>
                                </td>
                                @* add edit-details in class for modal*@
                                <td data-label="Ratee">
                                    <a  type="button" class="edit-details text-decoration-none theme-text"
                                       data-rid="@row.Ratee"
                                       data-relation="@row.Relation"
                                       data-name="@row.Ratee">
                                        @row.RateeName
                                    </a>
                                </td>
                
                                <td data-label="Action" class="text-nowrap sort-">
                                    <a type="button" class="btn btn-danger btn-icon"
                                       data-bs-toggle="modal"
                                       data-bs-target="#deleteModal"
                                       data-ratee="@row.Ratee">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-trash"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 7l16 0" /><path d="M10 11l0 6" /><path d="M14 11l0 6" /><path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" /><path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" /></svg>
                                    </a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>

            <div class="card-footer d-flex align-items-center">
                <ul class="pagination m-0 ms-auto"></ul>
            </div>


        </div>

    </div>
</div>



@using (Html.BeginForm("SaveMapping", "Mapping", FormMethod.Post, new { id = "form-save-details" }))
{

    @Html.HiddenFor(m => m.EVId)
    <!-- Modal -->
    <div class="modal fade" id="mapModal" tabindex="-1" aria-labelledby="mapModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="mapModalLabel">Employee Mapping</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label">Relation</label>
                        <select class="form-select tom-select" id="relation" asp-for="mapDetails.Relation" required>
                            <option value=""></option>
                            <option value="Head">Head</option>
                            <option value="Peers">Peers</option>
                            <option value="Direct Report">Direct Report</option>
                            <option value="Internal Customer">Internal Customer</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Ratee</label>
                        <select id="Ratee" class="form-select tom-select-subtitle" asp-for="mapDetails.Ratee" required>
                            <option value="" disabled selected>Select Employee</option>
                            @foreach (var item in Model.EmpList)
                            {
                                <option value="@item.EId" data-subtitle="@item.EId">@item.EmpName</option>
                            }
                        </select>
                    </div>



                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>

            </div>
        </div>
    </div>
}


<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">

            @using (Html.BeginForm("DeleteMapping", "Mapping", FormMethod.Post, new { id = "form-delete-details" }))
            {
                <div class="modal-header">
                    <h5 class="modal-title">Confirm Deletion</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <p>Are you sure you want to delete this mapping?</p>
                    @* You can include a hidden field for Id if needed *@
                    @Html.HiddenFor(m => m.EVId)
                    @Html.HiddenFor(m => m.mapDetails.Ratee, new { id = "Ratee" })
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>
            }

        </div>
    </div>
</div>


@using (Html.BeginForm("EditMapping", "Mapping", FormMethod.Post, new { id = "form-edit-details" }))
{
    @Html.HiddenFor(m => m.EVId)

    
    <!-- Edit Modal -->
    <div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editModalLabel">Edit Mapping Info</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label">Relation</label>
                        <select class="form-select" id="Relation1" asp-for="mapDetails.Relation" required>
                            <option value="" disabled selected></option>
                            <option value="Head">Head</option>
                            <option value="Peers">Peers</option>
                            <option value="Direct Report">Direct Report</option>
                            <option value="Internal Customer">Internal Customer</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Ratee</label>
                        <select id="Ratee2" class="form-select" asp-for="mapDetails.Ratee" disabled>
                            <option value="" disabled selected>Select Employee</option>
                            @foreach (var item in Model.EmpList)
                            {
                                <option value="@item.EId" data-subtitle="@item.EId">@item.EmpName</option>
                            }
                        </select>
                    </div>
                    @Html.HiddenFor(m => m.mapDetails.Ratee, new { id = "ratee1" })
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" >Save</button>
                </div>
            </div>
        </div>
    </div>
}


@section Scripts 
{

    <script>
        $(document).ready(function () {
            $('#deleteModal').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget); // Button that triggered the modal
                var ratee = button.data('ratee');    // Get data-ratee value

                // Set the value in the textbox
                $(this).find('#Ratee').val(ratee);
            });
        });


        
    </script>

    <script>
      

            // Event handler for modal trigger links
            $(document).on("click", ".edit-details", function () {
                let name = $(this).data("name");
                let relation = $(this).data("relation");
                let rateeid = $(this).data("rid");

                $("#Relation1").val(relation);
                $("#Ratee2").val(name);
                $("#ratee1").val(rateeid);
                


             $("#editModal").modal("show");
            });
   
    </script>
}